# Generated by Django 4.2.2 on 2023-06-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_kebumen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
