# Generated by Django 4.2.2 on 2023-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website_kebumen', '0002_delete_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
    ]
