# Generated by Django 4.2.2 on 2023-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_kebumen', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='image_file_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
