# Generated by Django 4.2.2 on 2023-06-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_kebumen', '0004_destinations_image_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='kategori',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='destinations',
            name='suka',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='nama',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Fasility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fasilitas', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_kebumen.destinations')),
            ],
        ),
    ]
