# Generated by Django 4.2.2 on 2023-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_kebumen', '0006_destinations_location_destinations_timeclose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasility',
            name='logo_file_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
