# Generated by Django 4.2.2 on 2023-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_kebumen', '0007_fasility_logo_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textInfografis', models.TextField()),
                ('kodePos', models.CharField(max_length=20)),
                ('Wilayah', models.CharField(max_length=20)),
                ('Penduduk', models.CharField(max_length=20)),
                ('Kepadatan', models.CharField(max_length=20)),
            ],
        ),
    ]
